[package]
name = "slang-sys"
version = "0.1.0"
edition = "2021"

[dependencies]
paste = "1.0.15"

[build-dependencies]
bindgen = "0.69.4"
cmake = { version = "0.1.50", optional = true }

[features]
default = []
static = ["cmake"]